browser/templates/base.html, browser/templates/edit_group_info.html, config/logging.conf, engine/constants.py, http_handler/settings.py, http_handler/static/css/base.css, http_handler/wsgi.py, schema/models.py, smtp_handler/main.py, smtp_handler/utils.py
Mostly pretty small changes. (I don't know how do-able it is to rename existing DB tables, so if you don't want that change let me know and I'll make a new pull request without it.) Only places I'm still finding "mailx" with grep are the readme and celeryconfig.py
=> Renamed occurrences of 'mailx' to 'murmur'; add tagging restrictions 

browser/templates/subscribe.html, browser/views.py, http_handler/urls.py, smtp_handler/main.py, smtp_handler/utils.py
If you send a message that starts with "subscribe" or "unsubscribe" followed by the newline character, the message handling will be transferred to the relevant route and you will subscribe/unsubscribe to the group. Fixes issue #51 
Those routes were not actually working (the function calls passed in the email address rather than the user object) so I fixed them. I ended up just copy-pasting in the try/except from another part of main.py. From what I can tell, in every part of the code where subscribe_group or unsubscribe_group is called, the call is preceded by a similar try/except (or get_object_or_404) to get the user via their email address. It might make sense to have the functions just take in the email address rather than user, and if the user is not found the function can return an …
=> Send "unsubscribe" to unsubscribe

smtp_handler/utils.py
added .docx, .xls, .xlsx, .pptx. fixes #77 
it might also be nice to add calendar files. I know there's .ics - not sure what else. full list of supported types now: jpg, bmp, png, pdf, txt, ppt, doc, xls, pptx, docx, xlsx.
=> more attachment file types 

smtp_handler/lamson_subclass.py, smtp_handler/utils.py
created MurmurMIMEPart to make all text/html encoded using quoted-printable; copied to_message from lamson/encoding.py and changed it to use MurmurMIMEPart
=> gmail quoting issue

browser/templates/group_page.html, browser/templates/groups.html, http_handler/static/javascript/main.js
as per @karger 's request the members list is not shown to non-admins. haven't done to show admin contact info yet, waiting until we decide on that. but this helps with the privacy concern for now anyway
=> hide group members for non-admins

browser/templates/group_page.html, engine/main.py, http_handler/static/javascript/group_page.js, requirements.txt, schema/models.py, smtp_handler/main.py
* list URL (if it exists) is shown in table
* if a message comes in with a message-id, we use that instead of creating our own. (the only time we make our own now is if someone posts from the murmur web interface.)
* when we receive a message, don't post it if any of the following are true:
1) it shares message-id with existing post to same group; 
2) in the last ten min, we received a post to same group from same sender with same subject line; 
3) we get a message where the "original sender" field (it seems that google groups adds this a murmur group posts to it) is our own group address. 
* fixed bug with looking up the associated mailing lists; wasn't checking if the list actually had permission to post before.
=> list forwarding fixes and de-duplication

browser/views.py
basically it wasn't working because we were missing msg_id argument to engine.main.insert_reply. and we can't use the msg_id that is sent in the post request because it's the one for the initial message in the thread already, and msg_ids have to be unique.
=> fixed issue with inserting replies on the web

browser/templates/squadbox/home.html, engine/constants.py, engine/main.py, schema/models.py, smtp_handler/main.py, smtp_handler/utils.py
the main changes here are 
- posts now have a "status" field that can be "approved", "pending", or "rejected". 
- new table for whitelist/blacklist info. 
- splitting up logic in smtp_handler/main.py to do things differently based on the website. for now, most of this is "do nothing if squadbox, do as before if murmur." besides in handle_post, which now branches to two separate functions and sends received emails to a group's moderators. 
because of the new table and the new field in Post, you will have to do a DB migration (just the auto/default one will work) when merging this into production.
=> message status; blacklist/whitelist; separating out mail server logic based on website

formEmails/formSubmission.js, formEmails/instructions.md, formEmails/logEditURL.js
- now we send a confirmation email to the form's submitter which contains the "edit response' URL
- added fields for category to the form, and these get put as tags at the bottom of the generated email
- added new script that runs in the spreadsheet where form data is stored and logs the edit response URL for each submission
- updated instructions a bit 
turns out that we do already allow underscores, just not dashes, so I switched to using those in multi-word tags.
minus the issue with emails getting flagged as suspicious (which is bigger than just this use case) I think this should finally be ready to go.... can demo it tomorrow at meeting
=> updated form submission code w/ tagging

http_handler/urls.py
this line appears later in the file already. having it where it was breaks all of the custom registration pages that need extra context (website name)
=> remove URL line

browser/templates/edit_group_info.html
have the correct radio buttons selected for whether a group is public/private and whether it allows attachments
=> group info not displayed correctly

smtp_handler/main.py
fixes the error we found yesterday with sender names that have non-ASCII characters.
=> fix error with special characters in 'from'

smtp_handler/utils.py
So as @oliverjd suggested, it is indeed lamson that is base64 encoding parts of messages before handing them off to us. I spent quite a while playing around with lamson functions and sample messages, and I *think* that the bug is happening as follows... (feel free to not read all of this, though it's mildly interesting... just wanted to thoroughly write it down in case we need to revisit later.) 
So basically, when we receive a message, Lamson first parses the message using its [from_message](https://github.com/zedshaw/lamson/blob/8a8ad546ea746b129fa5f069bf9278f87d01473a/lamson/encoding.py#L217) method and creates a new "pristine MailBase" object (recursively made up of more MailBase objects, one corresponds to each message part).
Then it converts this MailBase back to a normal Python …
=> hopefully fix decoding stuff

browser/views.py, engine/main.py, schema/models.py, smtp_handler/main.py, smtp_handler/utils.py
Changes here
- the previews of posts with HTML were displaying the HTML literally, so now convert to plaintext first. 
- no longer get the squadbox recipients in insert_post, because we insert both posts that need to be moderated and those that don't (rejected ones)
- two new fields added to Group table about what should happen to rejected posts. (you'll need to do a migration - auto should be fine.) 
- sorting out logic for what happens to an incoming post
- if sender is whitelisted, add a footer noting that, and send on to intended recipient 
- if sender is blacklisted, put message in DB with status rejected, and if user wants rejected messages, send on with [Rejected] tag and a footer explaining why
- otherwise, put in DB with status pending, send a notification to mods that a new …
=> logic for what happens to incoming posts

browser/templates/squadbox/base.html, browser/views.py, engine/main.py, schema/models.py, smtp_handler/main.py, smtp_handler/utils.py
this builds on some code from last PR, so I would deal with that one first. what's new here:
- when a pending post is approved, we create a new email message and send it to intended recipient.
- when a pending post is rejected, we see if user wants to receive rejected messages with a tag, and if so create a new email message and send it to intended recipient.
=> after mod approves/rejects, send to intended recipient

browser/templates/squadbox/thread.html, engine/attachments.py, engine/main.py, smtp_handler/main.py
when a post goes through moderation and is approved, we grab its attachments back from AWS and put them on the outgoing message.
=> Handle attachments on moderated posts

browser/templates/squadbox/thread.html, browser/views.py, engine/main.py, http_handler/static/css/squadbox/base.css, http_handler/static/javascript/squadbox/thread.js, schema/models.py
- added some extra post metadata fields to schema - auto migration should be fine. 
- depending on whether approve or reject is selected, show mod different additional options 
- if accept, mod can add sender to whitelist
- if reject, mod can add sender to blacklist, write an explanation, and/or add (for now) generic tags about content
- backend support for the tag and explanation features
- cleaned up duplicate logging statements (maybe from an auto-merge) in views.py
=> more moderation features

.gitignore, browser/templates/create_group.html, browser/templates/edit_group_info.html, browser/templates/squadbox/add_members.html, browser/templates/squadbox/edit_my_settings.html, browser/templates/squadbox/group_page.html, browser/views.py, engine/main.py, http_handler/static/css/squadbox/base.css, http_handler/static/filters/tag_archive_rejected.xml, http_handler/static/javascript/create_group.js, http_handler/static/javascript/edit_group_info.js
- upon creation and also in squad settings page, let admin set per-group/squad settings for whether rejected messages are sent out with a tag, and whether they are stored on the site 
- some reorganizing and cleanup on squad settings page
- added a shareable gmail filter for labeling + archiving messages with "[rejected]" in subject line
=> front-end support for rejected message settings

browser/templates/squadbox/base.html, browser/templates/squadbox/dashboard.html, browser/templates/squadbox/group_page.html, browser/templates/squadbox/rejected.html, browser/templates/squadbox/rejected_thread.html, browser/views.py, engine/main.py, http_handler/static/css/squadbox/base.css, http_handler/static/javascript/squadbox/rejected.js, http_handler/static/javascript/squadbox/rejected_thread.js, http_handler/urls.py, schema/models.py, smtp_handler/main.py
- new user field to store the name in an email's "From" field, if it exists. (for example if "Kaitlin Mahar <kmahar @ mit.edu>", stores "Kaitlin Mahar".) **you will need to do a migration - auto is fine.** 
- clean up base template / top menu bar for squadbox pages
- change the way multiple posts are listed on dashboard to look more like gmail 
- clean up html in group settings page 
- new admin views for seeing both a list of rejected posts, and for seeing an individual rejected post
- has a (not yet working) form for them to message moderator about the post 
- allow admins to permanently delete rejected posts from the site
=> more settings and interface for dealing with rejected posts 

browser/templates/squadbox/base.html, browser/templates/squadbox/dashboard.html, browser/templates/squadbox/group_page.html, browser/templates/squadbox/rejected.html, browser/templates/squadbox/rejected_thread.html, browser/views.py, engine/main.py, http_handler/static/css/squadbox/base.css, http_handler/static/javascript/squadbox/group_page.js, http_handler/static/javascript/squadbox/rejected.js, http_handler/static/javascript/squadbox/rejected_thread.js, http_handler/static/javascript/squadbox/thread.js, http_handler/urls.py, schema/models.py, smtp_handler/main.py, smtp_handler/utils.py
you'll want to look at my other PR first, as this branch has those changes merged in. 
this PR adds support for deactivating your squad. there's a button on the website to turn it off, and now when handling incoming emails in smtp_handler, we check if the squad is active. if it isn't, we just auto-approve the message and send it on with a footer "this message was automatically approved because you squad is deactivated".
=> ability to turn off squadbox

smtp_handler/main.py
very small fix - str() assumes all ASCII characters so throws an error when the subject line has something non-ASCII in it. If you explicitly tell it to encode as utf-8, then no error.
=> encode as utf-8 for subjects with non-ascii chars

smtp_handler/utils.py
This is just a quick fix to stop sending people those emails about verification until we implement the discussed changes.
=> don't send email about verification

browser/templates/edit_group_info.html, browser/templates/squadbox/moderate_user_thread.html, browser/views.py, engine/main.py, http_handler/static/javascript/edit_group_info.js, http_handler/static/javascript/squadbox/thread.js, http_handler/urls.py, schema/models.py, smtp_handler/main.py, smtp_handler/utils.py
uses code from the other PR i have open, so merge that one first (might be conflicts, lmk)
**you'll need to do an auto migration**
**changes**:
- frontend/backend for changing the auto-approve setting
- endpoints to click from email signature that turn moderation on/off for a sender+thread pair
- threadhash logic, if auto-approve setting is on: 
- we store a hash of sender|subject along with foreign key to the related group and a boolean indicating whether the owner has specifically opted in to continue moderation for this user
- when we get a post from a user, we see if threadhash for them exists
- if it does and moderate=True, post needs moderation (user opted in)
- if it does and moderate=False, auto-approve post (this is not their first post, and first one was approved) 
- if it …
=> Threadhash

browser/templates/edit_group_info.html, browser/templates/squadbox/group_page.html, browser/templates/squadbox/moderation_modal.html, browser/templates/squadbox/thread.html, browser/util.py, browser/views.py, engine/main.py, http_handler/static/javascript/edit_group_info.js, schema/models.py
I merged in the code from the other outstanding PR already, so hopefully won't be conflicts.
what's new here - a way for squad owners to enter prefs for their moderators. **you will need to do an auto migration for adding this**. later on we'll probably want to build this out and make it more complex, allow them to add formatting, have some suggested categories they can check off (for ex. profanity), etc. 
so I've added
1) a new field in the squad settings page where this info will be added/edited
2) that data is now displayed on the squad info page
3) on the page for a moderator reviewing a particular post, they can click a link that pops up a modal displaying the rules. I'm not sure if this is the best way to do that (mods might want to be able to view post and rules side-by-side) but …
=> spot for entering moderation rules/preferences

browser/util.py, browser/views.py, engine/main.py, engine/s3_storage.py, smtp_handler/main.py, smtp_handler/utils.py
I branched this off from prev PR w/ threadhash, so probably easier for you if you merge that first. 
**changes here:**
- Cleaned up logic in serve_attachment, added better error handling 
- Store full original messages in text form on S3 under [WEBSITE]/original_messages/[post id]_[msg_id]. This happens for all Murmur posts, and for Squadbox posts that get stored in DB (those that aren't auto approved.) todo: delete posts from S3 once post is approved? 
- Download the original messages from S3 to get some more header data (in-reply-to, references) before sending out approved posts.
- Fix some header stuff on all posts - In-Reply-To should be the message-id of a separate message that this is a reply to. and References should contain message-ids of all past messages this message was …
=> Store original messages on S3 

browser/templates/squadbox/mod_queue.html, browser/templates/squadbox/thread.html, browser/views.py, engine/main.py, http_handler/static/css/squadbox/base.css, http_handler/static/javascript/squadbox/thread.js, smtp_handler/main.py
again, needed code from previous PRs to do this, so this includes their code.
I was testing earlier and realized there was some weird behavior when multiple posts from the same thread were pending moderation. basically a link to the thread would show up multiple times in the queue, but would always only feature the first post to th thread. 
so this groups together pending posts by their thread, and indicates in the moderation queue that it is a multi-post thread. when a mod clicks on it, it will display all of them, and have them go one by one through all the thread's posts in order of time to approve/reject them. 
since the approve/reject page is the "thread" view from murmur, this required making a couple of logic changes to load_thread for deciding which post shows up as the primary …
=> Multiple pending in thread

browser/templates/squadbox/thread.html, browser/util.py, browser/views.py, engine/main.py, gmail_setup/api.py, gmail_setup/views.py, schema/models.py, smtp_handler/main.py, smtp_handler/utils.py
Ok so as we discussed last meeting, needed a way to differentiate moderated messages using gmail filters. I first implemented this as the [sender gmail]+[secret hash]@gmail thing, but for whatever reason, the mail relay was stripping out the secret hashes on outgoing messages - i.e. on our end it was sent to "xxxx+hash@gmail", but by the time it got to gmail the "to" field was simply "xxxx@gmail". I spent a long time trying to fix it and couldn't figure it out so I gave up.
so I ended up switching to the other solution we'd talked about with setting the list-id of the message to be hash@squadbox. these do not get stripped out, and I think this is actually better because (unlike when the hash is in the "to' field) the hash is *not* carried through in forwarded messages. (and it isn't in …
=> various improvements from testing 

.gitignore, browser/views.py, engine/main.py, http_handler/static/javascript/murmur/main.js, http_handler/urls.py, schema/models.py, smtp_handler/management/commands/digest.py, smtp_handler/utils.py
Currently, when a group page is loaded, Murmur fetches entire thread messages & attachments which makes super slow to load the page. 
Instead, I change when the page is loaded only metadata (e.g. the original author, number of msg at thread, first 20 letters of content) of each thread is loaded. And attachment& content of individual email are loaded when a user clicks a thread to view.
=> When group page is loaded, don't load entire message contents & attachments
