smtp_handler/main.py, smtp_handler/utils.py
Added an upvote link after the post permalink in email signatures
=> Upvote link

schema/models.py, smtp_handler/main.py, smtp_handler/utils.py
Moved code for dealing with attachments, getting subject and message body to utils.py
=> handle_post cleanup

smtp_handler/main.py, smtp_handler/utils.py
quick changes - wrote a function to send error emails and got rid of repetitive code
=> error email cleanup

browser/templates/group_page.html, browser/views.py, http_handler/static/javascript/main.js, smtp_handler/main.py, smtp_handler/utils.py
Since the member list is hidden, this still allows members to contact the admins of a list.
I think something similar this could be useful down the road for squadbox, as a way to contact the moderators for a particular user
=> added admin route

smtp_handler/main.py
I think this should fix the problem with confirmation emails not going through. Basically it was checking for "Account activation on murmur" but the expected subject is actually "Account activation on Murmur". Just converting everything to lowercase now to avoid the issue.
=> Confirmation emails issue

formEmails/formSubmission.js
fixed formatting for journal article volume and issue, and added a keywords field to the form.
=> Papers form updates

.gitignore, browser/templates/squadbox/home.html, browser/views.py, engine/constants.py, engine/main.py, http_handler/urls.py, schema/models.py, smtp_handler/main.py, smtp_handler/utils.py
this builds on/includes changes from the PR I made yesterday (#121) since it was dependent on them, so it will probably be easier for you to merge that one in first and then look at this afterward. or alternatively just only merge this one. 
new stuff:
- endpoints for approve, reject, blacklist, whitelist (links will go in email signatures)
- function to update a post's status 
- function to add/update a blacklist or whitelist entry 
- split up the URL patterns in urls.py based on website
=> Blacklist whitelist, approve and reject basics

engine/main.py
Issue #73 
Also deleted duplicated function in engine/main.py
=> Send an email to user if their member role is changed

browser/templates/murmur/add_list.html, browser/views.py, engine/main.py
improved wording for adding associated mailing lists. also some better error handling for issues on group info page (this is where I was getting that error because I hadn't migrated my DB)
=> better wording

smtp_handler/main.py
Now we look at all of the "to" emails, instead of just the first one, to see if they are a list that is authorized to post to the Murmur group.
=> Multiple "to" addresses bug

browser/templates/squadbox/base.html, browser/templates/whitelist.html, browser/views.py, http_handler/urls.py
basically identical to those for upvote, subscribe, etc.
=> endpoints for whitelisting and blacklisting

browser/templates/approve_reject.html, browser/views.py, http_handler/urls.py
- template + updated views for the GET approve/reject pages
- new views for POST requests to approve/reject posts
=> Approve and reject views

browser/templates/squadbox/dashboard.html, browser/templates/squadbox/thread.html, browser/views.py, engine/main.py, http_handler/static/css/squadbox/base.css, http_handler/static/javascript/squadbox/thread.js, http_handler/urls.py
New route at /dashboard for for moderation. loads pending posts in groups you are a mod for, allows you to approve or reject post as well as add its sender to whitelist/blacklist. 
moderation queue is basically just modified version of mobile post list on murmur; view for individual message is based on thread.html for murmur.
=> moderation dashboard

smtp_handler/utils.py
if content-transfer-encoding is base64, set decode to True
=> decoding bug

smtp_handler/utils.py
this should fix #177. we were checking for wrong subtype in message
=> fix 'plain' error message

browser/views.py
should fix the "add_members() takes exactly 4 arguments (3 given)" error
=> fix add_members problem

engine/main.py
Now as Lea suggested people will be able to add addresses in form
"Name 1 \<email1>, Name 2 \<email2>"
instead of just "email1, email2".
=> Add members input formatting

smtp_handler/main.py
sorry, somehow missed this before.
=> was overwriting res with some important data

gmail_setup/views.py
I had these commented so I could see gmail api errors in the browser, but they should be there to "fail gracefully"
=> forgot to uncomment these

browser/templates/squadbox/edit_create_group.html, schema/models.py, smtp_handler/main.py
default to this in DB, and when creating new squad check it by default
=> by default, check auto approve after first

browser/templates/registration/registration_form.html, browser/templates/squadbox/home.html, schema/models.py
feel free to edit this if you think wording should be different or something. just links to signup page so we can send to mozfest for them to look at. 
also, small model change I made manually back during user study but we should get into code.
=> links to register + small model change

browser/templates/murmur/login_email.html, browser/templates/murmur/mobile_list_posts.html, browser/views.py, engine/main.py, http_handler/static/javascript/murmur/login_imap.js, http_handler/urls.py
=> Posts pagination & lazy loading

browser/templates/murmur/mobile_list_posts.html, browser/templates/murmur/thread.html, browser/util.py, browser/views.py, smtp_handler/utils.py
Resolve
https://github.com/haystack/murmur/issues/230
https://github.com/haystack/murmur/issues/237
https://github.com/haystack/murmur/issues/238
https://github.com/haystack/murmur/issues/239
https://github.com/haystack/murmur/issues/241
https://github.com/haystack/murmur/issues/242
Also, this one is addressed at last PR but forgot to close it. Can you close it? I don't have access to close them. https://github.com/haystack/murmur/issues/232
=> Interface around Membership

README.md, scripts/new_database.sh
Updated based on changes to Docker setup make commands
=> Updated README for newer django version setup

browser/templates/murmur/create_post.html, http_handler/static/css/murmur/base.css, http_handler/static/javascript/murmur/create_post.js
=> Delete tag token
